# Generated by Django 3.1 on 2022-06-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosmodel',
            name='td',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
